# Generated by Django 2.1.4 on 2018-12-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='address',
            field=models.CharField(default='None', max_length=128),
        ),
    ]
